### PR TITLE
feat: update the exposed hardfork API to match Hardhat's definition

### LINKED ISSUE #1634: Update EDR hardfork to match Hardhat's
This is a follow-up of #1601 
 
- change `ProtocolHardfork` names to match HH. 
  - [This](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat/src/internal/builtin-plugins/network-manager/edr/types/hardfork.ts#L5) is Hardhat's enum for `L1HardforkNames` and `OpHardforkNames`. Conversion logic lives [here](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat/src/internal/builtin-plugins/network-manager/edr/utils/convert-to-edr.ts#L74).
  - Hardhat 2 uses a similar [conversion function](https://github.com/NomicFoundation/hardhat/tree/v2/packages/hardhat-core/src/internal#L46). Names for their hardfork names (L1 only) live [here](https://github.com/NomicFoundation/hardhat/blob/v2/packages/hardhat-core/src/internal/util/hardforks.ts#L8).
  
- remove unsupported hardforks at the type level. Cherry-pickable changes: 54eca32

### PR DESCRIPTION
**Pull request by anaPerezGhiglia**
Closes #1634. 

Now that the hardfork type is owned by EDR (#1601) instead of mirroring revm's `SpecId`, we can shape the exposed API freely: this PR aligns it with Hardhat's own hardfork definitions, which will enable removing the conversion layers in Hardhat that translate between Hardhat and EDR names on every boundary crossing.

### Breaking changes (TS API)

- Renamed the `SpecId` enum to `L1Hardfork`, mirroring `OpHardfork`. Discriminants are unchanged.
- Removed the pre-Byzantium L1 hardforks at the type level (`Frontier`, `FrontierThawing`, `Homestead`, `DaoFork`, `Tangerine`, `SpuriousDragon`). Forking a chain from a block that precedes its oldest supported hardfork now fails with an error naming that hardfork, instead of silently skipping hardfork validation.
- Renamed the hardfork name strings to Hardhat's camelCase definitions (e.g. `"Byzantium"` → `"byzantium"`, `"MuirGlacier"` → `"muirGlacier"`, `"Bedrock"` → `"bedrock"`). `l1HardforkToString`/`opHardforkToString` return the new names; `l1HardforkFromString`/`opHardforkFromString` and provider configs accept only them.
- Removed the exported hardfork name string constants (`BYZANTIUM`, …, `AMSTERDAM`, `BEDROCK`, …, `ISTHMUS`). Hardhat 3 imports them only in two test files; Hardhat 2 uses them in `convertToEdr.ts`, which already requires a rewrite for the changes above. Suggested instead to replace then with the corresponding enumToString function. E.g.: replace `OSAKA` with `l1HardforkToString(L1Hardfork.Osaka)`

### Internal changes

- The name strings are derived from the variants via a single `#[strum(serialize_all = "camelCase")]` directive, replacing the per-variant `serialize` overrides. The expected strings are pinned as literals in each crate's `name_round_trip` test, which is the guard against unintended renames.
- Removed the `hardfork::name` string-constant modules from `edr_chain_l1` and `edr_op`.
- The napi enums (`L1Hardfork`, `OpHardfork`) delegate parsing and string conversion to the domain types. The napi `OpHardfork` excludes `Jovian`/`Interop`, which are not exposed over N-API yet; its parse rejects them explicitly. Unit tests pin that the hand-written conversion tables between the napi and domain enums are inverses.

### Notes for reviewers

- The napi-layer Rust enum is now also named `L1Hardfork`, colliding grep-wise with `edr_chain_l1::L1Hardfork` (the OP side already had this collision). An alternative is a role-based Rust name (e.g. `ExposedL1Hardfork`) with `#[napi(js_name = "L1Hardfork")]`, keeping the TS API unchanged - open for discussion.

### Hardhat migration

Hardhat's `L1HardforkName`/`OpHardforkName` values are now exactly EDR's hardfork strings, so the string-conversion mappings in HH3's `convert-to-edr.ts` and HH2's `convertToEdr.ts` can collapse to pass-throughs for supported forks.

### CODE REVIEW

File: .changeset/wise-falcons-relate.md [hunk 1]
```diff
@@ -0,0 +1,7 @@
+---
+"@nomicfoundation/edr": minor
+---
+
+Renamed the hardfork name strings to match Hardhat's definitions: names are now camelCase (e.g. `"byzantium"`, `"muirGlacier"`, `"bedrock"`). `l1HardforkToString`/`opHardforkToString` return the new names, and `l1HardforkFromString`/`opHardforkFromString` and provider configs accept only them — passing an old-style name (e.g. `"Byzantium"`) fails.
```
[the remark this answers is not in the document]
Comment (anaPerezGhiglia) [reply .changeset/wise-falcons-relate.md:5]: addressed by [d43c58a](https://github.com/NomicFoundation/edr/pull/1645/commits/d43c58a02e2c47342e7ad34ca20a32f4a14afb4c)

File: crates/edr_napi/index.js [hunk 2]
```diff
@@ -600,44 +600,26 @@ module.exports.ReturnData = nativeBinding.ReturnData
...
-module.exports.HOMESTEAD = nativeBinding.HOMESTEAD
 module.exports.IncludeTraces = nativeBinding.IncludeTraces
-module.exports.ISTANBUL = nativeBinding.ISTANBUL
-module.exports.ISTHMUS = nativeBinding.ISTHMUS
 module.exports.L1_CHAIN_TYPE = nativeBinding.L1_CHAIN_TYPE
 module.exports.l1GenesisState = nativeBinding.l1GenesisState
+module.exports.L1Hardfork = nativeBinding.L1Hardfork
 module.exports.l1HardforkFromString = nativeBinding.l1HardforkFromString
 module.exports.l1HardforkLatest = nativeBinding.l1HardforkLatest
 module.exports.l1HardforkToString = nativeBinding.l1HardforkToString
```
[the remark this answers is not in the document]
Comment (anaPerezGhiglia) [reply crates/edr_napi/index.js:738]: addressed by [d43c58a](https://github.com/NomicFoundation/edr/pull/1645/commits/d43c58a02e2c47342e7ad34ca20a32f4a14afb4c)

File: patches/hardhat@2.28.4.patch [hunk 3]
```diff
@@ -339,18 +340,119 @@ index 23b0715c04680d560c779a40890217d96f60916f..11771582b3e38226fac624b9e10a7849
...
+-            return edr_1.PRAGUE;
+-        case hardforks_1.HardforkName.OSAKA:
+-            return edr_1.OSAKA;
+-        default:
+-            const _exhaustiveCheck = hardfork;
+-            throw new Error(`Unknown hardfork name '${hardfork}', this shouldn't happen`);
+-    }
++    // EDR's hardfork names match Hardhat's, so no conversion is needed. Names
++    // EDR does not support (e.g. pre-Byzantium) are rejected by EDR itself.
++    return hardfork;
```
[the remark this answers is not in the document]
Comment (anaPerezGhiglia) [reply patches/hardhat@2.28.4.patch:402]: test updated by [2e04258](https://github.com/NomicFoundation/edr/pull/1645/commits/2e042580d0c2d37d7e4cb8d0b3ecb5744ca8770a)

File: patches/hardhat@2.28.4.patch [hunk 4]
```diff
@@ -737,10 +839,154 @@ index 7e4276a589668b96c16243f547c0a2caecdb0d46..4636477ae060c71beadf065749aaa938
...
+-      return OSAKA;
+-    default:
+-      const _exhaustiveCheck: never = hardfork;
+-      throw new Error(
+-        `Unknown hardfork name '${hardfork as string}', this shouldn't happen`
+-      );
+-  }
++  // EDR's hardfork names match Hardhat's, so no conversion is needed. Names
++  // EDR does not support (e.g. pre-Byzantium) are rejected by EDR itself.
++  return hardfork;
```
[the remark this answers is not in the document]
Comment (anaPerezGhiglia) [reply patches/hardhat@2.28.4.patch:931]: This is false. `v2`'s `HardforkName.MERGE = "merge"`. See https://github.com/NomicFoundation/hardhat/blob/c2d21a652814a9c4bfa79c32022537c4f213a329/packages/hardhat-core/src/internal/util/hardforks.ts#L23

File: patches/hardhat@2.28.4.patch [hunk 5]
```diff
@@ -339,18 +340,119 @@ index 23b0715c04680d560c779a40890217d96f60916f..11771582b3e38226fac624b9e10a7849
...
+index 9f306964d32309a3a72626fd5d522d2066758821..53b7bcd1328b2bcf7ca82e2596ef0bc639553010 100644
 --- a/internal/hardhat-network/provider/utils/convertToEdr.js
 +++ b/internal/hardhat-network/provider/utils/convertToEdr.js
-@@ -1,6 +1,6 @@
+@@ -1,101 +1,20 @@
  "use strict";
  Object.defineProperty(exports, "__esModule", { value: true });
 -exports.httpHeadersToEdr = exports.edrTracingMessageToMinimalMessage = exports.edrTracingMessageResultToMinimalEVMResult = exports.edrTracingStepToMinimalInterpreterStep = exports.edrRpcDebugTraceToHardhat = exports.ethereumjsMempoolOrderToEdrMineOrdering = exports.ethereumjsIntervalMiningConfigToEdr = exports.edrSpecIdToEthereumHardfork = exports.ethereumsjsHardforkToEdrSpecId = void 0;
+-const edr_1 = require("@nomicfoundation/edr");
 +exports.httpHeadersToEdr = exports.edrTracingMessageToMinimalMessage = exports.edrTracingMessageResultToMinimalEVMResult = exports.edrTracingStepToMinimalInterpreterStep = exports.ethereumjsMempoolOrderToEdrMineOrdering = exports.ethereumjsIntervalMiningConfigToEdr = exports.edrSpecIdToEthereumHardfork = exports.ethereumsjsHardforkToEdrSpecId = void 0;
```
[the remark this answers is not in the document]
Comment (anaPerezGhiglia) [reply patches/hardhat@2.28.4.patch:351]: This is not part of this PR changes

File: crates/edr_op/src/hardfork.rs [hunk 6]
```diff
@@ -35,7 +35,7 @@ pub mod op;
     strum::EnumString,
     strum::IntoStaticStr,
 )]
-#[strum(parse_err_ty = UnknownHardfork, parse_err_fn = unknown_hardfork)]
+#[strum(serialize_all = "camelCase", parse_err_ty = UnknownHardfork, parse_err_fn = unknown_hardfork)]
```
[the remark this answers is not in the document]
Comment (anaPerezGhiglia) [reply crates/edr_op/src/hardfork.rs:38]: fixed by [b624ed7](https://github.com/NomicFoundation/edr/pull/1645/commits/b624ed7ebcb26fab53ed3e91f6e767e4dc6b2c48)

**Comment by anaPerezGhiglia** [comment]
Draft HH PR associated to these changes: NomicFoundation/hardhat#8574

File: .changeset/wise-falcons-relate.md (hunk 1 above)
Comment (Wodann) [inline .changeset/wise-falcons-relate.md]: Suggestion: match changelog terminology "Added/Removed/Changed [..]"

```suggestion
- Changed the hardfork name strings to match Hardhat's definitions: names are now camelCase (e.g. `"byzantium"`, `"muirGlacier"`, `"bedrock"`). `l1HardforkToString`/`opHardforkToString` return the new names, and `l1HardforkFromString`/`opHardforkFromString` and provider configs accept only them — passing an old-style name (e.g. `"Byzantium"`) fails.
```

File: crates/blockchain/fork/src/lib.rs [hunk 7]
```diff
@@ -72,17 +72,17 @@ pub enum ForkedBlockchainCreationError<HardforkT> {
         /// Latest block number
         latest_block_number: u64,
     },
-    /// The detected hardfork is not supported
+    /// The fork block predates the chain's oldest supported hardfork
     #[error(
-        "Cannot fork {chain_name} from block {fork_block_number}. The hardfork must be at least Spurious Dragon, but {hardfork:?} was detected."
+        "Cannot fork {chain_name} from block {fork_block_number}. The block precedes {oldest_hardfork:?}, which is the chain's oldest supported hardfork."
```
Comment (Wodann) [inline crates/blockchain/fork/src/lib.rs:77]: Now that we support `Display` for `HardforkT`, can this use the `Display` instead of the `Debug` trait implementation?

```suggestion
        "Cannot fork {chain_name} from block {fork_block_number}. The block precedes {oldest_hardfork}, which is the chain's oldest supported hardfork."
```

File: .changeset/mighty-poems-tickle.md [hunk 8]
```diff
@@ -0,0 +1,7 @@
+---
+"@nomicfoundation/edr": minor
+---
+
+Renamed the `SpecId` enum to `L1Hardfork`, mirroring `OpHardfork`, and removed support for pre-Byzantium Ethereum L1 hardforks: the enum no longer includes `Frontier`, `FrontierThawing`, `Homestead`, `DaoFork`, `Tangerine` and `SpuriousDragon`. Discriminants of the remaining variants are unchanged, so `Byzantium` is still `6`.
+
+Forking a chain from a block that precedes its oldest supported hardfork now fails with an error naming that hardfork, instead of silently skipping hardfork validation.
```
Comment (Wodann) [inline .changeset/mighty-poems-tickle.md]: Suggestion: Split up the changeset to explicitly call out the breaking change. Also conformed to the verbs used in the rest of the changelog: "Added/Fixed/Removed".

```suggestion
- Added `L1Hardfork` enum, with all post-Byzantium L1 hardforks. Discriminants of the variants match those of `SpecId`.
- Fixed an issue for forked blockchains where a block fork block that precedes its oldest supported hardfork was silently accepted. Now it fails with an error naming the oldest supported hardfork.
- BREAKING CHANGE: Removed `SpecId`. Instead, use `L1Hardfork`. Using any of the pre-Byzantium hardforks (`Frontier`, `FrontierThawing`, `Homestead`, `DaoFork`, `Tangerine` and `SpuriousDragon`) previously resulted in a runtime error. Now, they are no longer representable.
```

File: .changeset/wise-falcons-relate.md [hunk 9]
```diff
@@ -0,0 +1,7 @@
...
+
+The exported hardfork name string constants (`BYZANTIUM`, …, `AMSTERDAM` and `BEDROCK`, …, `ISTHMUS`) were removed; convert from the enum instead, e.g. replace `OSAKA` with `l1HardforkToString(L1Hardfork.Osaka)`. (Note that `L1Hardfork` is a numeric enum, so `L1Hardfork.Osaka.toString()` yields `"19"`, not the name.)
```
Comment (Wodann) [inline .changeset/wise-falcons-relate.md]: Suggestion: conform to changelog verbiage:

```suggestion
- BREAKING CHANGE: Removed hardfork name string constants (`BYZANTIUM`, …, `AMSTERDAM` and `BEDROCK`, …, `ISTHMUS`). Instead, obtain them using `l1HardforkToString` (e.g. replace `OSAKA` with `l1HardforkToString(L1Hardfork.Osaka)`).
```

File: crates/edr_op/src/hardfork.rs [hunk 10]
```diff
@@ -17,8 +17,8 @@ pub mod op;
 /// Models protocol upgrades, including ones without EVM-semantics changes,
 /// unlike [`op_revm::OpSpecId`] which models EVM behavior classes.
 ///
-/// The `strum(serialize = …)` strings must stay identical to the [`name`]
-/// module constants.
+/// The strum-derived names (`serialize_all = "camelCase"`) are public API;
+/// the expected strings are pinned in this module's tests.
```
Comment (Wodann) [inline crates/edr_op/src/hardfork.rs]: suggestion: this feels like a comment rather than a doc comment, since the user doesn't need to know.

The same applies to `L1Hardfork`.

```suggestion
// The strum-derived names (`serialize_all = "camelCase"`) are public API;
// the expected strings are pinned in this module's tests.
```

**Review by Wodann — APPROVED** [review]
Overall this looks good. However, I do have some suggestions w.r.t the wording of the changesets that I think should be applied to match our changelog, before merging.

Feel free to apply them locally and merge with re-approval; or ask me to have a quick look if you deem it necessary.

File: crates/blockchain/fork/src/lib.rs (hunk 7 above)
Comment (anaPerezGhiglia) [reply crates/blockchain/fork/src/lib.rs:77]: Not so easily. To use `Display` here we'd have to add a `Display` bound for `HardforkT` generic type of this enum, and since this error nests into `ProviderError`, the bound ripples through every generic consumer that renders provider errors. 
Containing that ripple means adding `Display` to the `ProtocolHardfork` umbrella trait itself, which I think goes against the style guide from #1618: error-formatting bounds belong at usage sites.
So I'd keep `Debug` formatting here, unless we want to deliberately declare `Display` part of `ProtocolHardfork`'s contract.

File: crates/edr_op/src/hardfork.rs (hunk 10 above)
Comment (anaPerezGhiglia) [reply crates/edr_op/src/hardfork.rs]: applied as part of [07a5b1e](https://github.com/NomicFoundation/edr/pull/1645/commits/07a5b1e9f9e5f237cf2b9729ceb25607b9f27abb)

**Comment by anaPerezGhiglia** [comment]
Regression benchmark failed because my branch was out of sync with `main` after #1673 which generated the 
```
Error: Cannot find module '/home/ubuntu/actions-runner/_work/edr/edr/.github/scripts/compute-sentinel-versions.ts'
```
